name: bazel

on:
  push:
    branches:
      - main
      
jobs:
  windows_msvc:
    runs-on: windows-latest
    steps:
      - run: choco upgrade llvm
      - uses: actions/checkout@v4.1.1
      - run: bazel test -c dbg ...
      - run: bazel test -c dbg --config=clang-cl ...
      - run: bazel test -c fastbuild ...
      - run: bazel test -c fastbuild --config=clang-cl ...
      - run: bazel test -c opt ...
      - run: bazel test -c opt --config=clang-cl ...
      - run: bazel test -c opt --test_output=streamed //src:dom_benchmarks
      - run: bazel test -c opt --test_output=streamed --config=clang-cl //src:dom_benchmarks
